.TH "bucket" 3 "Mardi 5 Décembre 2017" "CavBDM2 - BDD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bucket
.SH SYNOPSIS
.br
.PP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "size_t \fBc\fP"
.br
.ti -1c
.RI "struct \fBdiskWriter\fP * \fBdisk_out\fP"
.br
.ti -1c
.RI "int \fBcurrent_line\fP"
.br
.ti -1c
.RI "int \fBn_file\fP"
.br
.ti -1c
.RI "char * \fBdir\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
TP n°: 6
.PP
Titre du TP :
.PP
Date : 21/10/17
.PP
Nom : Lefranc Prenom : Joaquim email : lefrancjoaquim@gmail.com
.PP
Nom : Skoda Prenom : Jérôme email : contact@jeromeskoda.fr
.PP
Remarques : 
.SH "Documentation des données membres"
.PP 
.SS "size_t bucket::c"

.SS "int bucket::current_line"

.SS "char* bucket::dir"

.SS "struct \fBdiskWriter\fP* bucket::disk_out"

.SS "int bucket::n_file"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour CavBDM2 - BDD à partir du code source\&.
