.TH "diskManagerReader" 3 "Mardi 5 Décembre 2017" "CavBDM2 - BDD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
diskManagerReader
.SH SYNOPSIS
.br
.PP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "struct \fBdiskReader\fP ** \fBdr\fP"
.br
.ti -1c
.RI "size_t \fBdr_count\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
TP n°: 5
.PP
Titre du TP : Nested loop join disk
.PP
Date : 10 Nov 2017
.PP
Nom : Lefranc Prenom : Joaquim email : lefrancjoaquim@gmail.com
.PP
Nom : Skoda Prenom : Jérôme email : contact@jeromeskoda.fr
.PP
Remarques : 
.SH "Documentation des données membres"
.PP 
.SS "struct \fBdiskReader\fP** diskManagerReader::dr"

.SS "size_t diskManagerReader::dr_count"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour CavBDM2 - BDD à partir du code source\&.
