.TH "src/bdd/diskWriter.h" 3 "Mardi 5 Décembre 2017" "CavBDM2 - BDD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/bdd/diskWriter.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'buffer\&.h'\fP
.br
\fC#include 'diskReader\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "struct \fBdiskWriter\fP * \fBdisk_w_create\fP (const char *dir, const char *prefix, const char *extension)"
.br
.ti -1c
.RI "FILE * \fBdisk_w_get_current_f\fP (struct \fBdiskWriter\fP *disk_o)"
.br
.ti -1c
.RI "void \fBdisk_w_new_f\fP (struct \fBdiskWriter\fP *dw)"
.br
.ti -1c
.RI "void \fBdisk_w_destroy\fP (struct \fBdiskWriter\fP *disk_o)"
.br
.ti -1c
.RI "void \fBdisk_w_copy\fP (struct \fBdiskReader\fP *dr, struct \fBdiskWriter\fP *dw, struct \fBbuffer\fP *buf)"
.br
.ti -1c
.RI "char * \fBdisk_w_get_current_path\fP (struct \fBdiskWriter\fP *dw)"
.br
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "void disk_w_copy (struct \fBdiskReader\fP * dr, struct \fBdiskWriter\fP * dw, struct \fBbuffer\fP * buf)"

.SS "struct \fBdiskWriter\fP* disk_w_create (const char * dir, const char * prefix, const char * extension)"

.SS "void disk_w_destroy (struct \fBdiskWriter\fP * disk_o)"

.SS "FILE* disk_w_get_current_f (struct \fBdiskWriter\fP * disk_o)"

.SS "char* disk_w_get_current_path (struct \fBdiskWriter\fP * dw)"

.SS "void disk_w_new_f (struct \fBdiskWriter\fP * dw)"

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour CavBDM2 - BDD à partir du code source\&.
