.TH "diskWriter" 3 "Mardi 5 Décembre 2017" "CavBDM2 - BDD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
diskWriter
.SH SYNOPSIS
.br
.PP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "char * \fBdir\fP"
.br
.ti -1c
.RI "char * \fBprefix\fP"
.br
.ti -1c
.RI "char * \fBextension\fP"
.br
.ti -1c
.RI "int \fBfile_number\fP"
.br
.ti -1c
.RI "char * \fBcurrent_path\fP"
.br
.ti -1c
.RI "FILE * \fBcurrent_file\fP"
.br
.ti -1c
.RI "int \fBcurrent_line\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
TP n°: 5
.PP
Titre du TP : Nested loop join disk
.PP
Date : 10 Nov 2017
.PP
Nom : Lefranc Prenom : Joaquim email : lefrancjoaquim@gmail.com
.PP
Nom : Skoda Prenom : Jérôme email : contact@jeromeskoda.fr
.PP
Remarques : 
.SH "Documentation des données membres"
.PP 
.SS "FILE* diskWriter::current_file"

.SS "int diskWriter::current_line"

.SS "char* diskWriter::current_path"

.SS "char* diskWriter::dir"

.SS "char* diskWriter::extension"

.SS "int diskWriter::file_number"

.SS "char* diskWriter::prefix"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour CavBDM2 - BDD à partir du code source\&.
