.TH "diskManagerWriter" 3 "Mardi 5 Décembre 2017" "CavBDM2 - BDD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
diskManagerWriter \- Structure caché des données repésentant un \fBdiskManagerWriter\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "char * \fBdir\fP"
.br
.ti -1c
.RI "char * \fBd_prefixe\fP"
.br
.ti -1c
.RI "char * \fBd_suffixe\fP"
.br
.ti -1c
.RI "char * \fBf_prefixe\fP"
.br
.ti -1c
.RI "char * \fBf_suffixe\fP"
.br
.ti -1c
.RI "int \fBdw_number\fP"
.br
.ti -1c
.RI "struct \fBdiskWriter\fP * \fBcurrent_dw\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Structure caché des données repésentant un \fBdiskManagerWriter\fP\&. 

TP n°: 5
.PP
Titre du TP : Nested loop join disk
.PP
Date : 10 Nov 2017
.PP
Nom : Lefranc Prenom : Joaquim email : lefrancjoaquim@gmail.com
.PP
Nom : Skoda Prenom : Jérôme email : contact@jeromeskoda.fr
.PP
Remarques : TP n°: 5
.PP
Titre du TP : Nested loop join disk
.PP
Date : 10 Nov 2017
.PP
Nom : Lefranc Prenom : Joaquim email : lefrancjoaquim@gmail.com
.PP
Nom : Skoda Prenom : Jérôme email : contact@jeromeskoda.fr
.PP
Remarques : 
.SH "Documentation des données membres"
.PP 
.SS "struct \fBdiskWriter\fP* diskManagerWriter::current_dw"

.SS "char* diskManagerWriter::d_prefixe"

.SS "char* diskManagerWriter::d_suffixe"

.SS "char* diskManagerWriter::dir"

.SS "int diskManagerWriter::dw_number"

.SS "char* diskManagerWriter::f_prefixe"

.SS "char* diskManagerWriter::f_suffixe"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour CavBDM2 - BDD à partir du code source\&.
