.TH "src/bdd/quicksort.c" 3 "Vendredi 1 Décembre 2017" "CavBDM2 - BDD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/bdd/quicksort.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "void \fBchar_swap\fP (char *x, char *y)"
.br
.ti -1c
.RI "void \fBshort_swap\fP (short *x, short *y)"
.br
.ti -1c
.RI "int \fBchar_choose_pivot\fP (char i, char j)"
.br
.ti -1c
.RI "int \fBshort_choose_pivot\fP (short i, short j)"
.br
.ti -1c
.RI "void \fBchar_quicksort\fP (char *list, int m, int n)"
.br
.ti -1c
.RI "void \fBshort_quicksort\fP (short *list, int m, int n)"
.br
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "int char_choose_pivot (char i, char j)"

.SS "void char_quicksort (char * list, int m, int n)"

.SS "void char_swap (char * x, char * y)"
TP n°: 3
.PP
Titre du TP : Merge Join Duplicate
.PP
Date : 21/10/17
.PP
Nom : Lefranc Prenom : Joaquim email : lefrancjoaquim@gmail.com
.PP
Nom : Skoda Prenom : Jérôme email : contact@jeromeskoda.fr
.PP
Remarques : 
.SS "int short_choose_pivot (short i, short j)"

.SS "void short_quicksort (short * list, int m, int n)"

.SS "void short_swap (short * x, short * y)"

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour CavBDM2 - BDD à partir du code source\&.
