.TH "table" 3 "Vendredi 1 Décembre 2017" "CavBDM2 - BDD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
table \- Structure de donnée repésentant un buffer\&.  

.SH SYNOPSIS
.br
.PP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "struct \fBbucket\fP ** \fBb\fP"
.br
.RI "bucket "
.ti -1c
.RI "size_t \fBn_bucket\fP"
.br
.RI "n bucket "
.ti -1c
.RI "int \fBwrite_counter\fP"
.br
.RI "bench "
.in -1c
.SH "Description détaillée"
.PP 
Structure de donnée repésentant un buffer\&. 
.SH "Documentation des données membres"
.PP 
.SS "struct \fBbucket\fP** table::b"

.PP
bucket 
.SS "size_t table::n_bucket"

.PP
n bucket 
.SS "int table::write_counter"

.PP
bench 

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour CavBDM2 - BDD à partir du code source\&.
