.TH "src/bdd/diskReader.h" 3 "Mardi 5 Décembre 2017" "CavBDM2 - BDD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/bdd/diskReader.h
.SH SYNOPSIS
.br
.PP
\fC#include 'table\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "size_t \fBdisk_r_count\fP (const struct \fBdiskReader\fP *disk)"
.br
.ti -1c
.RI "struct \fBdiskReader\fP * \fBdisk_r_create\fP (const char *dir)"
.br
.ti -1c
.RI "void \fBdisk_r_destroy\fP (struct \fBdiskReader\fP *disk)"
.br
.ti -1c
.RI "FILE * \fBdisk_r_item\fP (const struct \fBdiskReader\fP *disk, int index)"
.br
.ti -1c
.RI "char * \fBdisk_r_item_path\fP (const struct \fBdiskReader\fP *disk, int index)"
.br
.ti -1c
.RI "void \fBdisk_r_storeContentInTable\fP (const struct \fBdiskReader\fP *disk, struct \fBbuffer\fP *buf, struct \fBtable\fP *tab)"
.br
.ti -1c
.RI "void \fBdisk_r_dump\fP (FILE *f, struct \fBdiskReader\fP *dr)"
.br
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "size_t disk_r_count (const struct \fBdiskReader\fP * disk)"

.SS "struct \fBdiskReader\fP* disk_r_create (const char * dir)"

.SS "void disk_r_destroy (struct \fBdiskReader\fP * disk)"

.SS "void disk_r_dump (FILE * f, struct \fBdiskReader\fP * dr)"

.SS "FILE* disk_r_item (const struct \fBdiskReader\fP * disk, int index)"

.SS "char* disk_r_item_path (const struct \fBdiskReader\fP * disk, int index)"

.SS "void disk_r_storeContentInTable (const struct \fBdiskReader\fP * disk, struct \fBbuffer\fP * buf, struct \fBtable\fP * tab)"

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour CavBDM2 - BDD à partir du code source\&.
