.TH "src/bdd/quicksort.h" 3 "Mardi 5 Décembre 2017" "CavBDM2 - BDD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/bdd/quicksort.h
.SH SYNOPSIS
.br
.PP
.SS "Fonctions"

.in +1c
.ti -1c
.RI "void \fBchar_quicksort\fP (char *list, char m, char n)"
.br
.ti -1c
.RI "void \fBshort_quicksort\fP (short *list, char m, char n)"
.br
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "void char_quicksort (char * list, char m, char n)"
TP n°: 3
.PP
Titre du TP : Merge Join Duplicate
.PP
Date : 21/10/17
.PP
Nom : Lefranc Prenom : Joaquim email : lefrancjoaquim@gmail.com
.PP
Nom : Skoda Prenom : Jérôme email : contact@jeromeskoda.fr
.PP
Remarques : Remarques : Ce fichier a été récuprer du site: http://www.zentut.com/c-tutorial/c-quicksort-algorithm/ il a été réadapté dans le cadre du projet 
.SS "void short_quicksort (short * list, char m, char n)"

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour CavBDM2 - BDD à partir du code source\&.
